---
# defaults file for role-teste
# PATH final com todos apps instalados (copiados de um hosts já configurado)
app_path: 'export PATH="$PATH:/usr/local/go/bin:${KREW_ROOT:-$HOME/.krew}/bin:/opt/kubectx:$HOME/.asdf/shims:$HOME/.asdf/bin"'

# ASDF
asdf_install: "yes"
asdf_version: "v0.13.1"

# AWS modo de instalação, opção pip ou apt
awscli_install_mode: "pip"

# Versão do AWS CLI - opção v1 ou v2
awscli_version: "v2"

# AWS IAM VERSION
iam_auth_version: "0.6.11"

# Docker Machine
docker_machine: "no"

# Golang
golang_version: "1.22.2"

# Home do Usuario
home_user: "/home/{{ ansible_user_id }}"

# Usuário
user_id: "{{ ansible_user_id }}"

# Helm
helm_package: "helm=3.13.2-1"

# Helm Diff version
helm_diff: "v3.8.1"

# Helm Secrets version
helm_secrets: "v4.5.1"

# Helm Docs
helm_docs_version: "1.11.3"
helm_docs_package: "helm-docs_{{ helm_docs_version }}_linux_x86_64.tar.gz"

# Helmfile
helmfile_version: "v0.144.0"
helmfile_downloaded_filename: "helmfile_linux_amd64"

# JJ
jj_version: "1.9.2"

# Krew
krew_package: "krew-linux_amd64"

# KubeFWD
kubefwd_version: "1.22.5"

# Kubepug
kubepug_version: "v1.4.0"

# Kubectl
kubectl_version: "1.29.4"

# Terraform docs
terraform_docs_version: "v0.16.0"

# Trivy
trivy_install: "yes"

# VSCode
install_vscode_plugins: "yes"

# YQ
# Nota: As versões 4.1.0 e recentes possuem a letra v antes do número da versão
# as versões mais antigas 4.0.0 e anteriores não possuem tal letra.
# Verificar a nomenclatura e alterar a variável antes de iniciar o playbook
yq_version: "v4.35.2"
yq_binary: "yq_linux_amd64"

# ZSH
powerlevel10k: "yes"
powerlevel10k_default: "yes"
zsh_install: "no"
