- name: Install asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{ home_user }}/.asdf"
    version: "{{ asdf_version }}"
    update: true
  when: asdf_install == 'yes'

- name: Check if bashrc exists
  stat:
    path: "{{ home_user }}/.bashrc"
  register: bashrc

- name: Check if zshrc exists
  stat:
    path: "{{ home_user }}/.zshrc"
  register: zshrc

- name: Add asdf to PATH (.bashrc)
  lineinfile:
    path: "{{ home_user }}/.bashrc"
    line: ". $HOME/.asdf/asdf.sh"
  when: asdf_install == 'yes' and bashrc.stat.exists

- name: Add completions (.bashrc)
  lineinfile:
    path: "{{ home_user }}/.bashrc"
    line: ". $HOME/.asdf/completions/asdf.bash"
  when: asdf_install == 'yes' and bashrc.stat.exists

- name: Add asdf to PATH (.zshrc)
  lineinfile:
    path: "{{ home_user }}/.zshrc"
    line: ". $HOME/.asdf/asdf.sh"
  when: asdf_install == 'yes' and zshrc.stat.exists

- name: Add completions (.zshrc)
  blockinfile:
    path: "{{ home_user }}/.zshrc"
    block: |
      # append completions to fpath
      fpath=(${ASDF_DIR}/completions $fpath)

      # initialise completions with ZSH's compinit
      autoload -Uz compinit && compinit
    create: true
    mode: 0644
  when: asdf_install == 'yes' and zshrc.stat.exists

- name: Install kubectl
  shell: |
    export ASDF_DIR="{{ home_user }}/.asdf"
    . $HOME/.asdf/asdf.sh &&
    asdf plugin-add kubectl https://github.com/asdf-community/asdf-kubectl.git &&
    asdf install kubectl {{ kubectl_version }} &&
    asdf global kubectl {{ kubectl_version }}
