# AWS CLI V1 via apt
- name: Installing AWS CLI via APT
  become: true
  apt:
    install_recommends: true
    name: awscli
  when: awscli_install_mode == "apt" and awscli_version == "v1"

# AWS CLI AWS CLI V1 via pip
- name: Installing AWS CLI via PIP
  shell:
    cmd: "python -m pip install awscli --upgrade --user"
  when: awscli_install_mode == "pip" and awscli_version == "v1"

# AWS CLI V2 via repo AWS
- name: Downloading AWS CLI V2
  unarchive:
    src: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/"
    remote_src: true
    creates: "/tmp/aws"
  when: awscli_version == "v2"

- name: Installing AWS CLI V2
  become: true
  shell:
    cmd: "/tmp/aws/install"
  when: awscli_version == "v2"

# Adicionar alias caso seja instalado via pip
- name: Check if bashrc exists
  stat:
    path: "{{ home_user }}/.bashrc"
  register: bashrc

- name: Append AWS CLI V1 PIP version alias to the .bashrc file.
  lineinfile:
    path: "{{ home_user }}/.bashrc"
    line: 'alias aws="python -m awscli"'
    state: present
  when: bashrc.stat.exists and awscli_install_mode == "pip" and awscli_version == "v1"

- name: Check if zshrc exists
  stat:
    path: "{{ home_user }}/.zshrc"
  register: zshrc

- name: Append AWS CLI V1 PIP version alias to the .zshrc file.
  lineinfile:
    path: "{{ home_user }}/.zshrc"
    line: 'alias aws="python -m awscli"'
    state: present
  when: zshrc.stat.exists and awscli_install_mode == "pip" and awscli_version == "v1"

# AWS SSM
- name: Installing AWS SSM on Ubuntu/Linux Mint
  become: true
  apt:
    deb: https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Linux Mint"

- name: Installing AWS SSM on openSUSE
  become: true
  community.general.zypper:
    name: "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm"
    disable_gpg_check: true
  when: ansible_distribution == "openSUSE Leap"

# AWS IAM Authentication
- name: Installing IAM Authentication
  become: true
  get_url:
    url: "https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v{{ iam_auth_version }}/aws-iam-authenticator_{{ iam_auth_version }}_linux_amd64"
    dest: "/usr/local/bin/aws-iam-authenticator"
    mode: "0755"
