# Instala a key do repository docker
- name: Install docker key
  become: true
  shell:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /usr/share/keyrings/docker.asc
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Linux Mint" or ansible_distribution == "Pop!_OS"

# cria o arquivo docker-ce em /etc/apt/sources.list.d/
- name: Install docker repository Ubuntu/Pop_OS
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker-ce
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Pop!_OS"

# cria o arquivo docker-ce em /etc/apt/sources.list.d/
- name: Install docker repository Mint
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable"
    state: present
    filename: docker-ce
  when: ansible_distribution == "Linux Mint" and ansible_distribution_major_version == "21"

# Instala o docker Ubuntu/Mint
- name: Install Docker packages on Ubuntu/Mint/Pop_OS
  become: true
  apt:
    update_cache: true
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Linux Mint" or ansible_distribution == "Pop!_OS"

# Instala o docker openSUSE
- name: Install Docker packages on openSUSE Leap
  become: true
  community.general.zypper:
    disable_recommends: false
    state: present
    pkg:
      - docker
      - docker-compose
      - docker-buildx
      - docker-compose-switch
      - docker-bash-completion
  when: ansible_distribution == 'openSUSE Leap'

# Adiciona o usuário ao grupo docker
- name: Adding existing user to group Docker
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true

# docker machine
- name: Copy Docker Machine from git
  become: true
  get_url:
    url: " https://github.com/docker/machine/releases/download/v0.16.2/docker-machine-$(uname -s)-$(uname -m)"
    dest: /tmp/docker-machine
  when: 'docker_machine == "yes"'

# Altera as permissões
- name: Changing permission of docker machine file
  become: true
  file:
    path: /tmp/docker-machine
    mode: "0755"
  when: 'docker_machine == "yes"'

# move o arquivo docker-machine para o destino
- name: Moving docker-machine file
  become: true
  shell:
    cmd: "mv /tmp/docker-machine /usr/local/bin/docker-machine"
  when: 'docker_machine == "yes"'
