# Instala a key do repository docker
- name: Install docker key
  become: true
  get_url:
    url: "https://download.docker.com/linux/{{ docker_repo_os }}/gpg"
    dest: /usr/share/keyrings/docker.asc
    mode: "0644"
  when: ansible_os_family == "Debian"

# cria o arquivo docker-ce em /etc/apt/sources.list.d/
# usa o codinome da base upstream (Mint 22 -> noble, Mint 21 -> jammy, Debian 13 -> trixie)
- name: Install docker repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker.asc] https://download.docker.com/linux/{{ docker_repo_os }} {{ upstream_codename }} stable"
    state: present
    filename: docker-ce
  when: ansible_os_family == "Debian"

# Instala o docker (apt)
- name: Install Docker packages (apt)
  become: true
  apt:
    update_cache: true
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  when: ansible_os_family == "Debian"

# Instala o docker openSUSE
- name: Install Docker packages on openSUSE Leap
  become: true
  community.general.zypper:
    disable_recommends: false
    state: present
    pkg:
      - docker
      - docker-compose
      - docker-buildx
      - docker-compose-switch
      - docker-bash-completion
  when: ansible_os_family == "Suse"

# Adiciona o usuário ao grupo docker
- name: Adding existing user to group Docker
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
