# Adiciona a key do repositório do Helm 3
- name: Add Helm Key
  become: true
  get_url:
    url: https://baltocdn.com/helm/signing.asc
    dest: /usr/share/keyrings/helm.asc
    mode: "0644"
    force: yes
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Linux Mint"

# Adiciona o repositório
- name: Add Helm repository
  become: true
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/helm.asc] https://baltocdn.com/helm/stable/debian/ all main"
    state: present
    filename: helm-stable-debian
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Linux Mint"

# Instala Helm 3
- name: Installing Helm package
  become: true
  apt:
    update_cache: true
    name: "{{ helm_package }}"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Linux Mint"

# openSUSE
- name: Install Docker packages on openSUSE Leap
  become: true
  community.general.zypper:
    disable_recommends: false
    state: present
    pkg:
      - helm
      - helm-bash-completion
      - helm-zsh-completion
      - helm-mirror
  when: ansible_distribution == 'openSUSE Leap'

# Adiciona o Helm Diff
- name: Add Helm Diff
  shell:
    cmd: "helm plugin install https://github.com/databus23/helm-diff --version {{ helm_diff }}"

# Adiciona o Helm Secrets
- name: Add Helm Secrets
  shell:
    cmd: "helm plugin install https://github.com/jkroepke/helm-secrets --version {{ helm_secrets }}"
