# Adiciona a key do repositório do Helm 3
- name: Add Helm Key
  become: true
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

# Adiciona o repositório
- name: Add Helm repository
  become: true
  apt_repository:
    repo: 'deb https://baltocdn.com/helm/stable/debian/ all main'
    state: present
    filename: helm-stable-debian

# Instala Helm 3
- name: Installing Helm package
  become: true
  apt:
    update_cache: yes
    name: '{{ helm_package }}'

# Adiciona repositorio helm especifico
#- name: Add Helm repository
#  shell:
#    cmd: 'helm repo add DESIRED REPO && helm repo update'

# Adiciona o Helm Diff
- name: Add Helm Diff
  shell:
    cmd: 'helm plugin install https://github.com/databus23/helm-diff --version {{helm_diff}}'

# Adiciona o Helm Secrets
- name: Add Helm Secrets
  shell:
    cmd: 'helm plugin install https://github.com/jkroepke/helm-secrets --version {{helm_secrets}}'
