# Exporta o $PATH e Instala kubectl tree
- name: Installing kubectl tree plugin
  shell:
    cmd: "{{ app_path }} && kubectl krew install tree"

# Exporta o $PATH e Instala node-shell
- name: Installing node-shell plugin
  shell:
    cmd: "{{ app_path }} && kubectl krew install node-shell"

# Instala o kubefwd
- name: Installing kubefwd on Ubuntu/Linux Mint/Pop_OS
  become: true
  apt:
    deb: https://github.com/txn2/kubefwd/releases/download/{{ kubefwd_version }}/kubefwd_amd64.deb
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Linux Mint" or ansible_distribution == "Pop!_OS"

- name: Installing kubefwd on openSUSE
  become: true
  community.general.zypper:
    name: https://github.com/txn2/kubefwd/releases/download/{{ kubefwd_version }}/kubefwd_amd64.rpm
    disable_gpg_check: true
  when: ansible_distribution == "openSUSE Leap"

# Instala kubepug
- name: Installing kubepug
  become: true
  unarchive:
    src: "https://github.com/kubepug/kubepug/releases/download/{{ kubepug_version }}/kubepug_linux_amd64.tar.gz"
    dest: /usr/local/bin
    remote_src: true

# Instala kubent
- name: Installing kubent
  become: true
  shell:
    cmd: 'sh -c "$(curl -sSL https://git.io/install-kubent)"'
