# Clona o repositório do kubectx
- name: Cloning git kubectx repository
  become: true
  git:
    repo: "https://github.com/ahmetb/kubectx"
    dest: "/opt/kubectx"

# Cria os links simbólicos
- name: Creating kubectx and kubens link
  become: true
  file:
    src: "/opt/kubectx/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  loop:
    - kubectx
    - kubens

# copia zsh completions
- name: Check if Oh-My-zsh completion folder exist
  stat:
    path: "{{ home_user }}/.oh-my-zsh/completions"
  register: zsh_completion

# se não existir cria o diretório
- name: Creating completions for Oh-My-zsh
  file:
    path: "{{ home_user }}/.oh-my-zsh/completions"
    state: directory
    mode: "0755"
  when: not zsh_completion.stat.exists and zsh_install == "yes"

# Cria um link dos arquivos de completion para o zsh
- name: Creating completions link
  file:
    src: "/opt/kubectx/completion/{{ item }}"
    dest: "{{ home_user }}/.oh-my-zsh/completions/{{ item }}"
    state: link
  loop:
    - _kubectx.zsh
    - _kubens.zsh
  when: zsh_install == "yes"
