# O Linux mint não tem suporte a snap
# e para instalar é preciso remover
# o arquivo nosnap que está em preferences.d
- name: Backup of nosnap file
  ignore_errors: true
  become: true
  copy:
    src: /etc/apt/preferences.d/nosnap.pref
    dest: ~/nosnap.backup
    mode: 0644
  when: ansible_distribution == 'Linux Mint'

- name: Removing nosnap file
  ignore_errors: true
  become: true
  file:
    path: /etc/apt/preferences.d/nosnap.pref
    state: absent
  when: ansible_distribution == 'Linux Mint'

- name: Update all Ubuntu/Mint packages to their latest version
  become: true
  apt:
    name: "*"
    update_cache: true
    cache_valid_time: 3600
    state: latest
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Linux Mint"

- name: Upgrade Ubuntu/Mint OS packages
  become: true
  apt:
    upgrade: dist
    update_cache: true
    cache_valid_time: 3600
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Linux Mint"

- name: Install OS packages Ubuntu/Mint
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600
    install_recommends: true
    state: present
    pkg:
      - apt-transport-https
      - bash-completion
      - build-essential
      - ca-certificates
      - curl
      - default-jdk
      - elinks
      - fzf
      - gnupg
      - htop
      - jq
      - lsb-release
      - meld
      - locate
      - mtr
      - mysql-client
      - net-tools
      - openssl
      - pass
      - p7zip-full
      - p7zip-rar
      - python3-pip
      - python3
      - python3-venv
      - redis-tools
      - snapd
      - tcpdump
      - telnet
      - tilix
      - traceroute
      - tree
      - vim
      - wget
      - whois
      - wireshark
      - zsh
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Linux Mint"

# Opensuse support

- name: Update all openSUSE Leap packages to their latest version
  become: true
  community.general.zypper:
    name: "*"
    update_cache: true
    state: latest
  when: ansible_distribution == 'openSUSE Leap'

- name: Perform openSUSE Leap dist-upgrade
  become: true
  community.general.zypper:
    name: "*"
    state: dist-upgrade
  when: ansible_distribution == 'openSUSE Leap'

- name: Install OS packages openSUSE Leap
  become: true
  community.general.zypper:
    disable_recommends: false
    state: present
    pkg:
      - bash-completion
      - ca-certificates
      - curl
      - elinks
      - fzf
      - gnupg
      - htop
      - jq
      - lsb-release
      - meld
      - mtr
      - mysql-client
      - net-tools
      - openssl
      - password-store
      - python3-pip
      - python3
      - python3-virtualenv
      - tcpdump
      - telnet
      - tilix
      - traceroute
      - tree
      - vim
      - wget
      - whois
      - wireshark
      - zsh
  when: ansible_distribution == 'openSUSE Leap'
