# Clona o repositório do tgenv
- name: Cloning git tgenv repository
  git:
    repo: "https://github.com/tgenv/tgenv.git"
    dest: "{{ home_user }}/.tgenv"

# lista os arquivos do diretorio
- name: Listing bin files in tgenv folder
  find:
    paths: "{{ home_user }}/.tgenv/bin"
  register: find

# Cria os links simbólicos
- name: Creating tgenv bin link
  become: true
  file:
    src: "{{ item.path }}"
    dest: "/usr/local/bin/{{ item.path | basename }}"
    state: link
  loop: "{{ find.files }}"

# Instala as versões do terraform
- name: Installing terragrunt versions
  shell:
    cmd: "tgenv install {{ item }}"
  loop:
    - 0.55.20
