- name: Add Trivy Key
  become: true
  get_url:
    url: https://aquasecurity.github.io/trivy-repo/deb/public.key
    dest: /usr/share/keyrings/trivy.asc
    state: present
  when: trivy_install == 'yes'

# cria o arquivo trivy.list no diretório /etc/apt/sources.list.d/
- name: Add Trivy repository
  become: true
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/trivy.asc] https://aquasecurity.github.io/trivy-repo/deb generic main"
    state: present
    filename: trivy.list
  when: trivy_install == 'yes'

# Instala o trivy
- name: Installing trivy package
  become: true
  apt:
    update_cache: true
    name: "trivy"
    state: latest
  when: trivy_install == 'yes'
