- name: Add Trivy Key on Ubuntu/Linux Mint
  become: true
  get_url:
    url: https://aquasecurity.github.io/trivy-repo/deb/public.key
    dest: /usr/share/keyrings/trivy.asc
    mode: "0644"
    force: yes
  when: (trivy_install == 'yes') or (ansible_distribution == "Ubuntu" or ansible_distribution == "Linux Mint")

# cria o arquivo trivy.list no diretório /etc/apt/sources.list.d/
- name: Add Trivy repository on Ubuntu/Linux Mint
  become: true
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/trivy.asc] https://aquasecurity.github.io/trivy-repo/deb generic main"
    state: present
    filename: trivy.list
  when: (trivy_install == 'yes') or (ansible_distribution == "Ubuntu" or ansible_distribution == "Linux Mint")

# Instala o trivy
- name: Install Trivy tool on Ubuntu/Linux Mint
  become: true
  apt:
    update_cache: true
    name: "trivy"
    state: latest
  when: (trivy_install == 'yes') or (ansible_distribution == "Ubuntu" or ansible_distribution == "Linux Mint")

# openSUSE
- name: Creating Trivy repository on openSUSE
  become: true
  copy:
    dest: /etc/zypp/repos.d/trivy.repo
    content: |
      [trivy]
      name=Trivy repository
      baseurl=https://aquasecurity.github.io/trivy-repo/rpm/releases/\$basearch/
      gpgcheck=1
      enabled=1
      gpgkey=https://aquasecurity.github.io/trivy-repo/rpm/public.key
    mode: 0644
  when: ansible_distribution == "openSUSE Leap"

- name: Install Trivy tool on openSUSE
  become: true
  community.general.zypper:
    update_cache: true
    disable_recommends: false
    state: present
    name: trivy
    extra_args_precommand: "--gpg-auto-import-keys"
  when: ansible_distribution == "openSUSE Leap"
