- name: Add Trivy Key
  become: true
  get_url:
    url: https://aquasecurity.github.io/trivy-repo/deb/public.key
    dest: /usr/share/keyrings/trivy.gpg
    state: present
  when: trivy_install == 'yes'

# cria o arquivo trivy.list no diretório /etc/apt/sources.list.d/
- name: Add Trivy repository
  become: true
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb {{ ansible_distribution_release }} main"
    state: present
    filename: trivy.list
  when: ansible_distribution == 'Ubuntu' and trivy_install == 'yes'

# cria o arquivo trivy.list no diretório /etc/apt/sources.list.d/
- name: Add Trivy repository
  become: true
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb jammy main"
    state: present
    filename: trivy.list
  when: ansible_distribution == 'Linux Mint' and ansible_distribution_major_version == '21' and trivy_install == 'yes'

# Instala o trivy
- name: Installing trivy package
  become: true
  apt:
    update_cache: true
    name: "trivy"
    state: latest
  when: trivy_install == 'yes'
