# Instalação do VSCode
- name: Install Microsoft Key on Ubuntu/Linux Mint
  become: true
  get_url:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    dest: "/usr/share/keyrings/microsoft.asc"
    mode: 0644
    force: yes
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Linux Mint"

- name: Install VSCode Repository on Ubuntu/Linux Mint
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.asc] https://packages.microsoft.com/repos/vscode stable main"
    state: present
    filename: vscode
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Linux Mint"

- name: Install Visual Studio Code on Ubuntu/Linux Mint
  become: true
  apt:
    name: code
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Linux Mint"

# openSUSE
- name: Creating VSCode repository on openSUSE
  become: true
  copy:
    dest: /etc/zypp/repos.d/vscode.repo
    content: |
      [code]
      name=Visual Studio Code
      baseurl=https://packages.microsoft.com/yumrepos/vscode
      enabled=1
      type=rpm-md
      gpgcheck=1
      gpgkey=https://packages.microsoft.com/keys/microsoft.asc
    mode: 0644
  when: ansible_distribution == "openSUSE Leap"

- name: Install VSCode on openSUSE
  become: true
  community.general.zypper:
    update_cache: true
    disable_recommends: false
    state: present
    name: code
    extra_args_precommand: "--gpg-auto-import-keys"
  when: ansible_distribution == "openSUSE Leap"

- name: Install Virtual Studio Code Extensions
  ignore_errors: true
  shell:
    cmd: code --install-extension '{{ item }}'
  loop:
    - ms-python.python
    - redhat.vscode-yaml
    - vscode-icons-team.vscode-icons
    - ms-vscode.cpptools
    - golang.go
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - hashicorp.terraform
    - bbenoist.vagrant
    - ms-ceintl.vscode-language-pack-pt-br
    - eamodio.gitlens
    - casualjim.gotemplate
    - ivory-lab.jenkinsfile-support
    - yzhang.markdown-all-in-one
    - DavidAnson.vscode-markdownlint
    - CharlesWan.markdown-toc
    - timonwong.shellcheck
    - HashiCorp.terraform
    - Tim-Koehler.helm-intellisense
    - gurumukhi.selected-lines-count
    - bierner.github-markdown-preview
    - bierner.markdown-checkbox
    - bierner.markdown-preview-github-styles
    - bierner.markdown-footnotes
    - bierner.markdown-emoji
    - ms-toolsai.jupyter
    - redhat.ansible
  when: install_vscode_plugins == 'yes'
