galaxy_info:
  author: Marcelo Primo
  description: Prepare workstation with devops tools.
  company: No company

  license: GPL

  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - "jammy"
        - "noble"
    - name: Linux Mint
      versions:
        - "victoria"
        - "vera"
        - "vanessa"
        - "virginia"
        - "xia"
        - "wilma"
        - "zena"
    - name: Debian
      versions:
        - "trixie"
    - name: openSUSE Leap
      versions:
        - "15.6"

  galaxy_tags:
    - terraform
    - terragrunt
    - awscli
    - kubectl
    - helm
    - golang
    - sops
    - mise

dependencies: []
