---
# Variáveis para a família Suse (openSUSE Leap)

os_packages:
  - bash-completion
  - ca-certificates
  - curl
  - elinks
  - flameshot
  - fzf
  - gnupg
  - gparted
  - htop
  - jq
  - lsb-release
  - meld
  - mtr
  - mysql-client
  - net-tools
  - openssl
  - password-store
  - python3-pip
  - python3
  - python3-virtualenv
  - tcpdump
  - telnet
  - tilix
  - traceroute
  - tree
  - vim
  - wget
  - whois
  - wireshark
  - zsh
