# AWS CLI via apt
- name: Installing AWS CLI
  become: true
  apt:
    install_recommends: yes
    name: awscli
  when: '{{ awscli_install_mode is match("apt") }}'

# AWS CLI via pip
- name: Installing AWS CLI
  shell:
    cmd: 'python -m pip install awscli --upgrade --user'
  when: '{{ awscli_install_mode is match("pip") }}'

# Adicionar alias caso seja instalado via pip
- name: Check if bashrc exists
  stat:
    path: '{{ home_user }}/.bashrc'
  register: bashrc

- name: Append alias at .bashrc file
  lineinfile:
    path: '{{ home_user }}/.bashrc'
    line: 'alias aws="python -m awscli"'
    state: present
  when: bashrc.stat.exists

- name: Check if zshrc exists
  stat:
    path: '{{ home_user }}/.zshrc'
  register: zshrc

- name: Append alias at .zshrc file
  lineinfile:
    path: '{{ home_user }}/.zshrc'
    line: 'alias aws="python -m awscli"'
    state: present
  when: zshrc.stat.exists

# AWS SSM
- name: Installing AWS SSM
  become: true
  apt:
    deb: https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb

# AWS IAM Authentication
- name: Downloading IAM Authentication
  become: true
  get_url:
    url: 'https://amazon-eks.s3-us-west-2.amazonaws.com/{{ iam_auth_version }}/2019-08-22/bin/linux/amd64/aws-iam-authenticator'
    dest: '/usr/local/bin/aws-iam-authenticator'
    mode: '0755'